# Mi primera red neuronal 🚀

En esta notebook, vamos a explorar la implementación de una red neuronal simple conocida como perceptrón. Un perceptrón es una unidad básica de una red neuronal que puede utilizarse para resolver problemas de clasificación binaria, como las funciones lógicas.

## Objetivos de Aprendizaje

Al final de esta notebook, serás capaz de:

1. Implementar un perceptrón simple en con las funciones lógicas (AND, OR, XOR) vistas en clase de dos formas diferentes:
    - Utilizando multiplicación de matrices ($sgn\left( X \, W \right)$).
    - Utilizando el sesgo ($sgn\left( X \, W + b \right)$).
2. [Opcional] Implementar el resto de las funciones lógicas (NAND, NOR, XNOR) utilizando perceptrones.
3. Implementar una Perceptrón Multicapa (MLP) para resolver el problema XOR.
4. [Opcional] Implementar un MLP para resolver las todas las funciones lógicas al mismo tiempo (AND, OR, XOR).


## Implementación de un Perceptrón

Un perceptrón es una unidad básica de una red neuronal que puede utilizarse para resolver problemas de clasificación binaria.

$$
\mathcal{P}(x; w) = sgn(x\, w) = sgn\left( \sum_i x_i w_i \right)
\quad x, w \in \mathbb{R}^m
$$
con
$$
 sgn(u) =
  \begin{cases}
   +1 & \text{if } u \geq 0 \\
   -1 & \text{if } u < 0
  \end{cases}
$$

En forma vectorial

$$\mathcal{P}(X; W) = sgn\left( X \, W \right) \quad X \in \mathbb{R}^{(n,m)}, \, W \in \mathbb{R}^{(m,1)}$$


### AND

La función lógica AND es una función que toma dos entradas binarias y devuelve 1 si ambas entradas son 1, y 0 en cualquier otro caso.

| $x_1$ | $x_2$ | $y$ |
|-------|-------|-----|
| 0     | 0     | 0   |
| 0     | 1     | 0   |
| 1     | 0     | 0   |
| 1     | 1     | 1   |


#### Implementación con multiplicación de matrices

$$
X = \begin{pmatrix}
  0 & 0 & 1 \\
  0 & 1 & 1 \\
  1 & 0 & 1 \\
  1 & 1 & 1 \\
 \end{pmatrix}
\qquad
\textbf{AND}\left( X \right) =
 \begin{pmatrix}
  -1 \\
  -1 \\
  -1 \\
  1  \\
 \end{pmatrix}
\qquad
n = 4
$$

> Notar que los valores esperados son -1 y 1 en lugar de 0 y 1.

$$
\textbf{AND}\left(X \right) = sgn\left( X \,   
    \begin{pmatrix}
      .5 \\
      .5 \\
      -1 \\
    \end{pmatrix} \right)
    \quad
    m = 3
$$

In [1]:
# Vamos a trabajar con PyTorch (tensores) para las operaciones matriciales
import torch

Definimos la función `sgn` que aplica la función signo a un número.

> Nota: pytorch tiene una función `torch.sign` pero difiere cuando la entrada es 0. En este caso, `torch.sign` devuelve 0 y `sgn` devuelve 1.
Más información en: https://pytorch.org/docs/stable/generated/torch.sign.html


In [2]:
def sgn(x):
    return torch.where(x >= 0, 1.0, -1.0)

Definimos `X` y `W` como tensores de pytorch, es importante definir el tipo de dato como `torch.float32` para que las operaciones matriciales se realicen correctamente.

In [5]:
X = torch.tensor([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]], dtype=torch.float32)

# TODO
W_and = torch.tensor([[.5], [.5], [-1]], dtype=torch.float32)

torch.matmul(X, W_and)

tensor([[-1.0000],
        [-0.5000],
        [-0.5000],
        [ 0.0000]])

In [6]:
X @ W_and

tensor([[-1.0000],
        [-0.5000],
        [-0.5000],
        [ 0.0000]])

Por último, calculamos el resultado de la función AND.

In [8]:
def AND(Input):
    return sgn(torch.matmul(Input, W_and)) 

print(f"{AND(X) = }")

AND(X) = tensor([[-1.],
        [-1.],
        [-1.],
        [ 1.]])


Vemos que el resultado es el esperado.

$$
\textbf{AND}\left( X \right) =
 \begin{pmatrix}
  -1 \\
  -1 \\
  -1 \\
  1  \\
 \end{pmatrix}
\qquad
$$

In [9]:
res = AND(torch.tensor([1, 0, 1], dtype=torch.float32))
print(f"{res = }")

res = tensor([-1.])


#### Implementación con sesgo (X W + b)

Ahora vamos a implementar la función AND utilizando un sesgo, es decir agregando un término adicional a la multiplicación de matrices.

Por lo cual nuestro X ahora es de la forma:

$$
X = \begin{pmatrix}
  0 & 0 \\
  0 & 1 \\
  1 & 0 \\
  1 & 1 \\
 \end{pmatrix}
$$

Y nuestro W y b son:

$$
W = \begin{pmatrix}
  .5 \\
  .5 \\
  \end{pmatrix}
\qquad
b = -1
$$

In [10]:
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)

W_and = torch.tensor([[.5], [.5]], dtype=torch.float32)
b = torch.tensor(-1, dtype=torch.float32)

In [11]:
def AND(Input):
    return sgn(torch.matmul(Input, W_and) + b)

Notar `b` hace brodcasting, ya que es un escalar y `X` es una matriz.

Más información en:
- https://numpy.org/doc/stable/user/basics.broadcasting.html
- https://pytorch.org/docs/stable/notes/broadcasting.html 

In [12]:
AND(X)

tensor([[-1.],
        [-1.],
        [-1.],
        [ 1.]])

### OR

La función lógica OR es una función que toma dos entradas binarias y devuelve 1 si al menos una de las entradas es 1, y 0 en cualquier otro caso.

| $x_1$ | $x_2$ | $y$ |
|-------|-------|-----|
| 0     | 0     | 0   |
| 0     | 1     | 1   |
| 1     | 0     | 1   |
| 1     | 1     | 1   |


#### Implementación con multiplicación de matrices

$$
X = \begin{pmatrix}
  0 & 0 & 1 \\
  0 & 1 & 1 \\
  1 & 0 & 1 \\
  1 & 1 & 1 \\
 \end{pmatrix}
\qquad
\textbf{OR}\left( X \right) =
 \begin{pmatrix}
  -1 \\
  1 \\
  1 \\
  1  \\
 \end{pmatrix}
\qquad
n = 4
$$


$$
\textbf{OR}\left(X \right) = sgn\left( X \,   
    \begin{pmatrix}
      ? \\
      ? \\
      ? \\
    \end{pmatrix} \right)
    \quad
    m = 3
$$

In [13]:
X = torch.tensor([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]], dtype=torch.float32)

W_nor = torch.tensor([[.5], [.5], [-1]], dtype=torch.float32)
W_or = torch.tensor([[1.], [1.], [-1]], dtype=torch.float32)

In [14]:
def OR(Input):
    return sgn(torch.matmul(Input, W_or))


print(f"{OR(X) = }")

OR(X) = tensor([[-1.],
        [ 1.],
        [ 1.],
        [ 1.]])


#### Implementación con sesgo (X W + b)

$$
X = \begin{pmatrix}
  0 & 0 \\
  0 & 1 \\
  1 & 0 \\
  1 & 1 \\
 \end{pmatrix}
$$

Y nuestro W y b son:

$$
W = \begin{pmatrix}
  ? \\
  ? \\
  \end{pmatrix}
\qquad
b = ?
$$

In [19]:
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)

W_or = torch.tensor([[1.], [1.]])
b_or = torch.tensor(-1.)

def OR(Input):
    return sgn(torch.matmul(Input, W_or) + b_or)

print(f"{OR(X) = }")

OR(X) = tensor([[-1.],
        [ 1.],
        [ 1.],
        [ 1.]])


### XOR

La función lógica XOR es una función que toma dos entradas binarias y devuelve 1 si las entradas son diferentes, y 0 si son iguales.

| $x_1$ | $x_2$ | $y$ |
|-------|-------|-----|
| 0     | 0     | 0   |
| 0     | 1     | 1   |
| 1     | 0     | 1   |
| 1     | 1     | 0   |

#### Implementación con multiplicación de matrices

$$
X = \begin{pmatrix}
  0 & 0 & 1 \\
  0 & 1 & 1 \\
  1 & 0 & 1 \\
  1 & 1 & 1 \\
 \end{pmatrix}
\qquad
\textbf{XOR}\left( X \right) =
 \begin{pmatrix}
  -1 \\
  1 \\
  1 \\
  -1  \\
 \end{pmatrix}
\qquad
n = 4
$$

$$
\textbf{XOR}\left(X \right) = sgn\left( X \,   
    \begin{pmatrix}
      ? \\
      ? \\
      ? \\
    \end{pmatrix} \right)
    \quad
    m = 3
$$

In [37]:
# Defino las entradas con bias
X = torch.tensor([
    [0, 0, 1],  # x1=0, x2=0, bias=1
    [0, 1, 1],  # x1=0, x2=1, bias=1
    [1, 0, 1],  # x1=1, x2=0, bias=1
    [1, 1, 1],  # x1=1, x2=1, bias=1
], dtype=torch.float32)

# Salida esperada de XOR
y = torch.tensor([[-1], [1], [1], [-1]], dtype=torch.float32)

def step(x):
    return torch.where(x >= 0, torch.tensor(1.0), torch.tensor(0.0))

# Capa de dos perceptrones para calcular AND y OR (con bias)
W1 = torch.tensor([
    [1, 1, -1.5],   
    [1, 1, -0.5], 
])

# Capa que combina AND y OR para obtener XOR
W2 = torch.tensor([[1, -2, -0.5]])  # Ajustados a mano

# Salida de capa 1
h1 = step(X @ W1.T)

# bias que se suma a la salida de la primera capa
h1_b = torch.cat([h1, torch.ones((h1.shape[0], 1))], dim=1)

# Salida final (XOR)
output = step(h1_b @ W2.T)

print(output)
print("Esperado:")
print(y)

tensor([[0.],
        [0.],
        [0.],
        [0.]])
Esperado:
tensor([[-1.],
        [ 1.],
        [ 1.],
        [-1.]])


### [Opcional] Implementar el resto de las funciones lógicas (NAND, NOR, XNOR) utilizando perceptrones.

#### NAND

| $x_1$ | $x_2$ | $y$ |
|-------|-------|-----|
| 0     | 0     | 1   |
| 0     | 1     | 1   |
| 1     | 0     | 1   |
| 1     | 1     | 0   |


In [40]:
# Definimos X sin bias
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)

# NAND: solo es 0 cuando ambos son 1.
W_nand = torch.tensor([[-1.0, -1.0, 1.5]])

# Concatenamos bias a las entradas
X_b = torch.cat([X, torch.ones((X.shape[0], 1))], dim=1) 

output_nand = step(X_b @ W_nand.T)
print("Salida NAND:")
print(output_nand)


Salida NAND:
tensor([[1.],
        [1.],
        [1.],
        [0.]])


#### NOR

| $x_1$ | $x_2$ | $y$ |
|-------|-------|-----|
| 0     | 0     | 1   |
| 0     | 1     | 0   |
| 1     | 0     | 0   |
| 1     | 1     | 0   |

In [52]:
X = torch.tensor([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]], dtype=torch.float32)

W_nor = torch.tensor([[-1], [-1], [1]], dtype=torch.float32)

def NOR(Input):
    return sgn(torch.matmul(Input, W_nor))

print(f"{NOR(X) = }")



NOR(X) = tensor([[ 1.],
        [ 1.],
        [ 1.],
        [-1.]])


#### NXOR

| $x_1$ | $x_2$ | $y$ |
|-------|-------|-----|
| 0     | 0     | 1   |
| 0     | 1     | 0   |
| 1     | 0     | 0   |
| 1     | 1     | 1   |


In [55]:
def NXOR(Input):
    W_nxor = torch.tensor([[1], [1], [-1]], dtype=torch.float32)
    return sgn(torch.matmul(Input, W_nxor))

print(f"{NXOR(X) = }")



NXOR(X) = tensor([[-1.],
        [ 1.],
        [ 1.],
        [ 1.]])


## XOR con Perceptrón Multicapa (MLP)

Para resolver el problema XOR, necesitamos una red neuronal más compleja, como una Perceptrón Multicapa (MLP).

In [64]:
import torch.nn as nn
import torch.optim as optim


# Redefinimos X sin bias (solo las dos entradas)
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
# Salidas esperadas (0 y 1 para BCELoss)
y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)

In [65]:
# Definimos el modelo
class XORNet(nn.Module):
    def __init__(self):
        super(XORNet, self).__init__()
        # Capa de entrada: 2 features -> 2 neuronas ocultas
        self.input = nn.Linear(2, 2)
        # Capa de salida: 2 neuronas ocultas -> 1 salida
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        # Primera capa con activación sigmoid
        x = torch.sigmoid(self.input(x))
        # Segunda capa con activación sigmoid
        x = torch.sigmoid(self.output(x))
        return x
    
# Alternativa usando Sequential
xor_seq = torch.nn.Sequential(
    nn.Linear(2, 2),
    nn.Sigmoid(),
    nn.Linear(2, 1),
    nn.Sigmoid()
)

In [66]:
# Instanciamos
model = XORNet()
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [67]:
# training loop
epochs = 10_000

for epoch in range(epochs):
    model.train()  # traing mode

    output = model(X)
    loss = criterion(output, y)

    optimizer.zero_grad()  # reseteamos los gradientes
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 1_000 == 0:
        print(f"Epoch [{(epoch + 1)}/epochs], Loss: {loss.item():.4f}")

Epoch [1000/epochs], Loss: 0.6931
Epoch [2000/epochs], Loss: 0.6931
Epoch [3000/epochs], Loss: 0.6930
Epoch [4000/epochs], Loss: 0.6929
Epoch [5000/epochs], Loss: 0.6924
Epoch [6000/epochs], Loss: 0.6901
Epoch [7000/epochs], Loss: 0.6699
Epoch [8000/epochs], Loss: 0.5764
Epoch [9000/epochs], Loss: 0.4163
Epoch [10000/epochs], Loss: 0.1294


In [ ]:
# evaluando el modelo
model.eval()

with torch.no_grad():
    output = model(X)
    output = torch.where(output < 0.5, 0, 1)
    print(output)

tensor([[0],
        [1],
        [1],
        [0]])


## [Opcional] Implementar una MLP para resolver las todas las funciones lógicas al mismo tiempo (AND, OR y XOR).


| $x_1$ | $x_2$ | $y_{AND}$ | $y_{OR}$ | $y_{XOR}$ |
|-------|-------|-----------|----------|-----------|
| 0     | 0     | 0         | 0        | 0         |
| 0     | 1     | 0         | 1        | 1         |
| 1     | 0     | 0         | 1        | 1         |
| 1     | 1     | 1         | 1        | 0         |


In [69]:
# Entradas
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
# Salidas esperadas
y = torch.tensor([[0, 0, 0], [0, 1, 1], [0, 1, 1], [1, 1, 0]], dtype=torch.float32)


# Definimos el modelo para las tres funciones
class LogicNet(nn.Module):
    def __init__(self):
        super(LogicNet, self).__init__()
        # Capa oculta: 2 entradas -> 4 neuronas 
        self.hidden = nn.Linear(2, 4)
        # Capa de salida: 4 neuronas -> 3 salidas (AND, OR, XOR)
        self.output = nn.Linear(4, 3)
        
    def forward(self, x):
        # Capa oculta con activación sigmoid
        x = torch.sigmoid(self.hidden(x))
        # Capa de salida con activación sigmoid
        x = torch.sigmoid(self.output(x))
        return x

In [71]:
# Instanciamos el modelo
model = LogicNet()
criterion = nn.BCELoss()  # Binary Cross Entropy para clasificación binaria
optimizer = optim.SGD(model.parameters(), lr=0.5)  # Learning rate más alto para convergencia más rápida

In [73]:
# Training loop
epochs = 10000
print_every = 1000

for epoch in range(epochs):
    model.train()
    
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, y)
    
    # Backward pass y optimización
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % print_every == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

Epoch [1000/10000], Loss: 0.0040
Epoch [2000/10000], Loss: 0.0036
Epoch [3000/10000], Loss: 0.0033
Epoch [4000/10000], Loss: 0.0030
Epoch [5000/10000], Loss: 0.0028
Epoch [6000/10000], Loss: 0.0026
Epoch [7000/10000], Loss: 0.0024
Epoch [8000/10000], Loss: 0.0023
Epoch [9000/10000], Loss: 0.0021
Epoch [10000/10000], Loss: 0.0020


In [74]:
# Evaluación
model.eval()
with torch.no_grad():
    predictions = model(X)
    print("\nPredicciones finales:")
    print("X1 X2 | AND  OR  XOR")
    print("-" * 20)
    for i, pred in enumerate(predictions):
        x1, x2 = X[i]
        and_pred, or_pred, xor_pred = pred
        print(f"{int(x1)}  {int(x2)}  | {and_pred:.2f} {or_pred:.2f} {xor_pred:.2f}")
    
    # Redondeamos para ver las predicciones binarias
    binary_pred = (predictions >= 0.5).float()
    print("\nPredicciones redondeadas:")
    print("X1 X2 | AND OR XOR")
    print("-" * 20)
    for i, pred in enumerate(binary_pred):
        x1, x2 = X[i]
        and_pred, or_pred, xor_pred = pred
        print(f"{int(x1)}  {int(x2)}  | {int(and_pred)}   {int(or_pred)}   {int(xor_pred)}")


Predicciones finales:
X1 X2 | AND  OR  XOR
--------------------
0  0  | 0.00 0.00 0.00
0  1  | 0.00 1.00 1.00
1  0  | 0.00 1.00 1.00
1  1  | 1.00 1.00 0.00

Predicciones redondeadas:
X1 X2 | AND OR XOR
--------------------
0  0  | 0   0   0
0  1  | 0   1   1
1  0  | 0   1   1
1  1  | 1   1   0
